name: portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  auto_scrolling: ^0.4.0
  font_awesome_flutter: '>= 4.7.0'
  flutter_social_button: ^1.1.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Removed the duplicate entry here
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/work_asset/
    - assets/logos/
    - assets/background/back.jpg

  fonts:
    - family: Meringue
      fonts:
        - asset: assets/fonts/meringue.OTF
          weight: 800
      
    - family: Baro
      fonts:
        - asset: assets/fonts/barostico.OTF
    
    - family : Aktiv
      fonts:
        - asset: assets/fonts/AktivGrotesk.OTF

    - family : SpaceR
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf

    - family : SpaceB
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf

    - family : SpaceSB
      fonts:
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf

    - family : Alata
      fonts:
        - asset: assets/fonts/Alata.ttf